import SideBar from "@/components/DashBoard/SideBar/SideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`dark:bg-black flex w-full max-h-screen`}>
      <SideBar />
      <div
        className="flex-1 h-full w-full
      "
      >
        {children}
      </div>
    </div>
  );
}
