import "./globals.css";
import ThemeProviderTailwind from "@/components/ThemeProvider/ThemeProvider";

import { lobsterTwo, roboto } from "@/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lobsterTwo.variable} ${roboto.variable}  font-roboto`}
      >
        <ThemeProviderTailwind>{children}</ThemeProviderTailwind>
      </body>
    </html>
  );
}
