import MainLayout from "@/components/MainLayout/MainLayout";
import "./globals.css";
import ThemeProviderTailwind from "@/components/ThemeProvider/ThemeProvider";

import { lobsterTwo, lora } from "@/fonts/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lobsterTwo.variable} ${lora.variable}  font-lora  dark:bg-black`}
      >
        <ThemeProviderTailwind>
          <MainLayout>{children}</MainLayout>
        </ThemeProviderTailwind>
      </body>
    </html>
  );
}
