import MainLayout from "@/components/MainLayout/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`dark:bg-black`}>
      {" "}
      <MainLayout>{children}</MainLayout>
    </div>
  );
}
